name: audio
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - eventlet
  - scipy
  - python-socketio
  - python-kaleido
  - plotly
  - nidaqmx-python
  - dash
  - librosa
  - flask-socketio
  - flask-cors
  - frozendict
  - dash-mantine-components
  - websocket-client
  - watchdog
  - simple-websocket
  - pip:
      - dash-iconify==0.1.2
      - pyaudio==0.2.14
      - praat-parselmouth
